#!/bin/bash
source $PENZSH_CMD_DIR/.core

function penzsh_cmd_do()
{
	pzcore_func_require "which cewl" "sudo apt-get install cewl"
	pzcore_func_require "which john" "sudo apt-get install john"
	if [ "$?" = 0 ] ; then
		mkdir -p $pzcore_dir_enum/wordlists
		read "REPLY?Enter port of service: "
		pzcore_func_is_ssl ${pzcore_target}:$REPLY
                if [ "$?" = 0 ] ; then
			pzcore_func_proxycmd cewl ${@:1} -w $pzcore_dir_enum/wordlists/cewl-http-$REPLY-$pzcore_timestamp.txt http://${pzcore_target}:$REPLY
			john --wordlist=$pzcore_dir_enum/wordlists/cewl-http-$REPLY-$pzcore_timestamp.txt --rules --stdout > $pzcore_dir_enum/wordlists/cewlrules-http-$REPLY-$pzcore_timestamp.txt
		else
			pzcore_func_proxycmd cewl ${@:1} -w $pzcore_dir_enum/wordlists/cewl-https-$REPLY-$pzcore_timestamp.txt https://${pzcore_target}:$REPLY
			john --wordlist=$pzcore_dir_enum/wordlists/cewl-https-$REPLY-$pzcore_timestamp.txt --rules --stdout > $pzcore_dir_enum/wordlists/cewlrules-https-$REPLY-$pzcore_timestamp.txt
		fi
	fi
}

function penzsh_cmd_info()
{
	echo -e "Runs cewl for both http/https on $pzcore_target for the specified port with the specified args, then uses john to apply rules."
}
