#!/bin/bash
source $PENZSH_CMD_DIR/.core

function penzsh_cmd_do()
{
	pzcore_func_require "which dirb" "sudo apt-get install dirb"
	if [ "$?" = 0 ] ; then
		mkdir -p $pzcore_dir_enum/dirb
		read "REPLY?Enter port of service: "
		pzcore_func_is_ssl ${pzcore_target}:$REPLY
                if [ "$?" = 0 ] ; then
			$pzcore_cmds_prefix dirb http://${pzcore_target}:$REPLY/ ${PENZSH_WORDLIST_WEBENUM} ${@:1} -o $pzcore_dir_enum/dirb/http-$REPLY.$pzcore_timestamp.dirb
		else
			$pzcore_cmds_prefix dirb https://${pzcore_target}:$REPLY/ ${PENZSH_WORDLIST_WEBENUM} ${@:1} -o $pzcore_dir_enum/dirb/https-$REPLY.$pzcore_timestamp.dirb
		fi
	fi
}

function penzsh_cmd_info()
{
	echo -e "Runs dirb for both http/https on $pzcore_target for the specified port with the specified args."
}
