#!/bin/bash
source $PENZSH_CMD_DIR/.core

function penzsh_cmd_do()
{
	pzcore_func_require "which enum4linux" "sudo apt-get install enum4linux"
	if [ "$?" = 0 ] ; then
		mkdir -p $pzcore_dir_enum/smb
		enum4linux ${@:1} $pzcore_target | tee $pzcore_dir_enum/smb/enum4linux-custom.$pzcore_timestamp.e4l
	fi
}

function penzsh_cmd_info()
{
	echo -e "Runs 'enum4linux <args> $pzcore_target'."
}
