#!/bin/bash
source $PENZSH_CMD_DIR/.core

function penzsh_cmd_do()
{
	pzcore_func_require "which ffuf" "sudo apt-get install ffuf"
	if [ "$?" = 0 ] ; then
		mkdir -p $pzcore_dir_enum/web
		mkdir -p $pzcore_dir_enum/web/ffuf
		read "REPLY?Enter port of service: "
		pzcore_func_is_ssl ${pzcore_target}:$REPLY
                if [ "$?" = 0 ] ; then
			pzcore_func_proxycmd ffuf -u http://${pzcore_target}:$REPLY/FUZZ -w ${PENZSH_WORDLIST_WEBENUM} ${@:1} -of all -o $pzcore_dir_enum/web/ffuf_formats/http-$REPLY.$pzcore_timestamp | tee $pzcore_dir_enum/web/ffuf-http-$REPLY.$pzcore_timestamp.txt
		else
			pzcore_func_proxycmd ffuf -u https://${pzcore_target}:$REPLY/FUZZ -w ${PENZSH_WORDLIST_WEBENUM} ${@:1} -of all -o $pzcore_dir_enum/web/ffuf_formats/https-$REPLY.$pzcore_timestamp | tee $pzcore_dir_enum/web/ffuf-https-$REPLY.$pzcore_timestamp.txt
		fi
	fi
}

function penzsh_cmd_info()
{
	echo -e "Runs ffuf for both http/https on $pzcore_target for the specified port with the specified args."
}
