#!/bin/bash
source $PENZSH_CMD_DIR/.core

function penzsh_cmd_do()
{
	pzcore_func_require "which ftp" "sudo apt-get install ftp"
	if [ "$?" = 0 ] ; then
		mkdir -p $pzcore_dir_loot/ftp
		cd $pzcore_dir_loot/ftp
		ftp $pzcore_target ${a:1}
		cd -
	fi
}

function penzsh_cmd_info()
{
	echo -e "Runs 'ftp $pzcore_target <args>' and makes the working directory $pzcore_dir_loot/ftp"
}
