#!/bin/bash
source $PENZSH_CMD_DIR/.core

function penzsh_cmd_do()
{
	pzcore_func_require "which gobuster" "sudo apt-get install gobuster"
	if [ "$?" = 0 ] ; then
		mkdir -p $pzcore_dir_enum/web
		read "REPLY?Enter port of service: "
		pzcore_func_is_ssl ${pzcore_target}:$REPLY
                if [ "$?" = 0 ] ; then
			gobuster dir --url=http://${pzcore_target}:$REPLY/ --wordlist ${PENZSH_WORDLIST_WEBENUM} ${@:1} -o $pzcore_dir_enum/web/gobuster-http-$REPLY.$pzcore_timestamp.txt
		else
			gobuster dir --url= https://${pzcore_target}:$REPLY/ --wordlist ${PENZSH_WORDLIST_WEBENUM} ${@:1} -o $pzcore_dir_enum/web/gobuster-https-$REPLY.$pzcore_timestamp.txt
		fi
	fi
}

function penzsh_cmd_info()
{
	echo -e "Runs gobuster for both http/https on $pzcore_target for the specified port with the specified args."
}
