#!/bin/bash
source $PENZSH_CMD_DIR/.core

function penzsh_cmd_do()
{
	pzcore_func_require "which nmap" "sudo apt-get install nmap"
	if [ "$?" = 0 ] ; then
		mkdir -p $pzcore_dir_enum/nmap
		if ( $pzcore_proxy ) ; then
			pzcore_func_proxycmd nmap -n -sT -Pn $pzcore_target -oA $pzcore_dir_enum/nmap/custom.$pzcore_timestamp ${@:1}
		else
			nmap $pzcore_target -oA $pzcore_dir_enum/nmap/custom.$pzcore_timestamp ${@:1}
		fi
	fi
}

function penzsh_cmd_info()
{
	echo -e "Runs 'nmap $pzcore_target -oA $pzcore_dir_enum/nmap/custom.<timestamp> <args>'."
}
