#!/bin/bash
source $PENZSH_CMD_DIR/.core

function penzsh_cmd_do()
{
	pzcore_func_require "dpkg -l exploitdb" "sudo apt-get install exploitdb"
	pzcore_func_require "dpkg -l exploitdb-papers" "sudo apt-get install exploitdb-papers"
	pzcore_func_require "dpkg -l exploitdb-bin-sploits" "sudo apt-get install exploitdb-bin-sploits"
	if [ "$?" = 0 ] ; then
		mkdir -p $pzcore_dir_research/searchsploit
		pzcore_func_echo "===SEARCHSPLOIT RESEARCH RESULTS==="
		searchsploit ${@:1} | tee $pzcore_dir_research/$(pzcore_func_validate_filename "${@:1}").$pzcore_timestamp.searchsploit.txt
	fi
}

function penzsh_cmd_info()
{
	echo -e "Ensures that exploitdb-papers and exploitdb-bin-sploits is installed."
	echo -e "Runs 'searchsploit <args> | tee %pzcore_dir_research/searchsploit/<args>.$pzcore_timestamp.txt'"
}
