#!/bin/bash
source $PENZSH_CMD_DIR/.core

function penzsh_analysis_analyze()
{
	if [[ "$PENZSH_ANALYSIS" = "full" || "$PENZSH_ANALYSIS" = "partial" ]] ; then
		pzcore_func_echo "Starting Analysis..."
		pzcore_func_require "which python3" "sudo apt-get install python3"
		if [ "$?" = 0 ] ; then
			pzcore_func_require "which pip3" "sudo apt-get install python3-pip"
			if [ "$?" = 0 ] ; then
				pzcore_func_require "pip3 list | grep \"yara-python\"" "pip3 install yara-python"
				if [ "$?" = 0 ] ; then
					python3 $PENZSH_ANALYSIS_DIR/analyze.py
				fi
			fi
		fi
	fi
}
